<?php

namespace App\Http\Controllers\Api_app;

use Illuminate\Http\Request;

class EmojiController extends AuthController
{
    public function emoji()
    {
        $emoji = [
            "😀" => "Cười tươi",
            "😃" => "Cười rạng rỡ",
            "😄" => "Cười lớn",
            "😁" => "Cười nhe răng",
            "😆" => "Cười nghiêng ngả",
            "😅" => "Cười ra mồ hôi",
            "😂" => "Cười ra nước mắt",
            "🤣" => "Cười lăn lộn",
            "☺️" => "Cười nhẹ nhàng",
            "😊" => "Cười hạnh phúc",
            "😇" => "Cười thiên thần",
            "🙂" => "Cười bình thường",
            "🙃" => "Cười lộn ngược",
            "😉" => "Nháy mắt",
            "😍" => "Yêu thích",
            "🥰" => "Yêu thương",
            "😘" => "Hôn gió",
            "😗" => "Hôn nhẹ",
            "😙" => "Hôn vui vẻ",
            "😚" => "Hôn thân mật",
            "😋" => "Thèm ăn",
            "😛" => "Thè lưỡi vui vẻ",
            "😝" => "Thè lưỡi tinh nghịch",
            "😜" => "Nháy mắt thè lưỡi",
            "🤪" => "Mặt khùng",
            "🤨" => "Nghi ngờ",
            "🧐" => "Suy xét",
            "🤓" => "Mặt mọt sách",
            "😎" => "Ngầu",
            "🤩" => "Mê mẩn",
            "🥳" => "Ăn mừng",
            "😏" => "Đểu cáng",
            "😒" => "Chán nản",
            "😞" => "Buồn",
            "😔" => "Trầm tư",
            "😟" => "Lo lắng",
            "😕" => "Bối rối",
            "🙁" => "Không vui",
            "☹️" => "Buồn rầu",
            "😣" => "Căng thẳng",
            "😖" => "Khó chịu",
            "😫" => "Mệt mỏi",
            "😩" => "Kiệt sức",
            "🥺" => "Năn nỉ",
            "😢" => "Khóc",
            "😭" => "Khóc to",
            "😤" => "Tức giận",
            "😠" => "Giận dữ",
            "😡" => "Rất giận",
            "🤬" => "Chửi thề",
            "🤯" => "Nổ não",
            "😳" => "Bối rối đỏ mặt",
            "🥵" => "Nóng nực",
            "🥶" => "Lạnh cóng",
            "😶‍🌫️" => "Mờ mịt",
            "😱" => "Sốc",
            "😨" => "Lo sợ",
            "😰" => "Sợ hãi",
            "😥" => "Buồn lo",
            "😓" => "Ra mồ hôi",
            "🤗" => "Ôm",
            "🤔" => "Suy nghĩ",
            "🤭" => "Cười thầm",
            "🤫" => "Suỵt!",
            "🤥" => "Nói dối",
            "😶" => "Im lặng",
            "😐" => "Vô cảm",
            "😑" => "Chán chường",
            "🙂‍↔️" => "Mặt trung lập 2 chiều",
            "🙂‍↕️" => "Mặt trung lập dọc",
            "😬" => "Cắn răng",
            "🙄" => "Trợn mắt",
            "😯" => "Ngạc nhiên nhẹ",
            "😦" => "Sững sờ",
            "😧" => "Kinh ngạc",
            "😮" => "Ngạc nhiên",
            "😲" => "Sốc nặng",
            "🥱" => "Ngáp",
            "😴" => "Ngủ",
            "🤤" => "Chảy nước miếng",
            "😪" => "Buồn ngủ",
            "😮‍💨" => "Thở phào",
            "😵" => "Choáng váng",
            "😵‍💫" => "Chóng mặt",
            "🤐" => "Khóa miệng",
            "🥴" => "Xỉn",
            "🤢" => "Buồn nôn",
            "🤮" => "Nôn mửa",
            "🤧" => "Hắt xì",
            "😷" => "Đeo khẩu trang",
            "🤒" => "Ốm",
            "🤕" => "Bị thương",
            "🤑" => "Tham tiền",
            "🤲" => "Hai tay mở hướng lên",
            "👐" => "Hai tay mở ra",
            "🙌" => "Giơ hai tay ăn mừng",
            "👏" => "Vỗ tay",
            "🤝" => "Bắt tay",
            "👍" => "Ngón cái lên (like)",
            "👎" => "Ngón cái xuống (dislike)",
            "👊" => "Đấm",
            "✊" => "Nắm tay giơ lên",
            "🤛" => "Đấm trái",
            "🤜" => "Đấm phải",
            "🤞" => "Bắt chéo ngón tay (cầu may)",
            "✌️" => "Hai ngón tay (Victory)",
            "🤟" => "Yêu bạn (ngôn ngữ ký hiệu)",
            "🤘" => "Rock on",
            "👌" => "OK",
            "🤏" => "Nhúm một chút",
            "👈" => "Chỉ trái",
            "👉" => "Chỉ phải",
            "👆" => "Chỉ lên",
            "👇" => "Chỉ xuống",
            "☝️" => "Giơ một ngón lên",
            "✋" => "Giơ tay lên",
            "🤚" => "Giơ tay ngược",
            "🖐️" => "Bàn tay có 5 ngón",
            "🖖" => "Chào kiểu Star Trek",
            "👋" => "Vẫy tay chào",
            "🤙" => "Gọi tôi nhé (Shaka)",
            "💪" => "Cơ bắp (mạnh mẽ)"
        ];

        // Nếu muốn trả về dạng array of objects:
        $result = [];
        foreach ($emoji as $symbol => $desc) {
            $result[] = [
                'emoji' => $symbol,
                'description' => $desc,
            ];
        }

        return response()->json([
            'data' => $result
        ]);
    }
}
